spring:
  datasource:
    url: jdbc:postgresql://db-ipsen5-do-user-16136531-0.c.db.ondigitalocean.com:25060/defaultdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: XksbXmLsdw3v9kGFcHyQG4waU9BlQvgpn5Tdo4Sns6V3QoiqrEVfxX0FhcEArA5g
  expiration: 86400000

server:
  port: 8080
  address: 159.223.228.6
  ssl:
    key-store: /etc/ssl/keystore.p12
    key-store-password: ipsen5
    key-store-type: PKCS12
    key-alias: www.websiteiprwc.site