spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres2
    username: postgres2
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: XksbXmLsdw3v9kGFcHyQG4waU9BlQvgpn5Tdo4Sns6V3QoiqrEVfxX0FhcEArA5g
  expiration: 86400000

server:
  error:
    include-stacktrace: never

