package ipsen5.models.enums;

public enum Rights {
    GETTEN,
    POSTEN,
    UPDATEN,
    DELETEN,
    ALL,

    GUARD_ROLES,
    GUARD_USER_ROLES,
    GUARD_SUBMISSIONS,
    GUARD_NOTIFICATIONS,
    REVIEW_SUBMISSIONS,

    SUBMISSION,
    SUBMISSION_GET,
    SUBMISSION_POST,
    SUBMISSION_PUT,
    SUBMISSION_DELETE,

    CATEGORY,
    CATEGORY_GET,
    CATEGORY_POST,
    CATEGORY_PUT,
    CATEGORY_DELETE,

    CRITERIA,
    CRITERIA_GET,
    CRITERIA_POST,
    CRITERIA_PUT,
    CRITERIA_DELETE,

    FEEDBACKPERELEMENT,
    FEEDBACKPERELEMENT_GET,
    FEEDBACKPERELEMENT_POST,
    FEEDBACKPERELEMENT_PUT,
    FEEDBACKPERELEMENT_DELETE,

    POST,
    POST_GET,
    POST_POST,
    POST_PUT,
    POST_DELETE,

    POSTCATEGORY,
    POSTCATEGORY_GET,
    POSTCATEGORY_POST,
    POSTCATEGORY_PUT,
    POSTCATEGORY_DELETE,

    RATING,
    RATING_GET,
    RATING_POST,
    RATING_PUT,
    RATING_DELETE,

    REACTION,
    REACTION_GET,
    REACTION_POST,
    REACTION_PUT,
    REACTION_DELETE,

    ROLE,
    ROLE_GET,
    ROLE_POST,
    ROLE_PUT,
    ROLE_DELETE,

    ROLEPRIVILIGES,
    ROLEPRIVILIGES_GET,
    ROLEPRIVILIGES_POST,
    ROLEPRIVILIGES_PUT,
    ROLEPRIVILIGES_DELETE,

    RUBRIC,
    RUBRIC_GET,
    RUBRIC_POST,
    RUBRIC_PUT,
    RUBRIC_DELETE,

    SOCIALMEDIA,
    SOCIALMEDIA_GET,
    SOCIALMEDIA_POST,
    SOCIALMEDIA_PUT,
    SOCIALMEDIA_DELETE,

    STATUS,
    STATUS_GET,
    STATUS_POST,
    STATUS_PUT,
    STATUS_DELETE,

    USER,
    USER_GET,
    USER_POST,
    USER_PUT,
    USER_DELETE
}
